Repository TheWorldAvatar/stack, pull requests merged in 2025-05, with the labels that each got.

#29 Increase rdf4j healthcheck retry number
  stack-clients/docker-compose.yml
  stack-clients/pom.xml
  stack-clients/src/main/resources/com/cmclinnovations/stack/services/built-ins/rdf4j.json
  stack-data-uploader/docker-compose.yml
  stack-data-uploader/pom.xml
  stack-manager/docker-compose.yml
  stack-manager/pom.xml
Labels: 🐛 bug

#31 Extended the documentation regarding the outgoing federation repository
  stack-manager/README.md
Labels: 📄 documentation

#34 Separate podman client lib
  stack-clients/docker-compose.yml
  stack-clients/pom.xml
  stack-clients/src/main/java/com/cmclinnovations/stack/clients/docker/PodmanClient.java
  stack-clients/src/main/java/com/cmclinnovations/stack/services/PodmanService.java
  stack-clients/src/main/java/com/github/dockerjava/jaxrs/ApiClientExtension.java
  stack-data-uploader/docker-compose.yml
  stack-data-uploader/pom.xml
  stack-manager/docker-compose.yml
  stack-manager/pom.xml
Labels: ✨ enhancement

#38 37-uploader-fails-due-to-rdf4j-with-podman: Fix #37
  stack-data-uploader/docker-compose-podman.yml
Labels: 🐛 bug

#39 A few additions to the troubleshooting section of the podman readme.
  stack-manager/README-podman.md
Labels: 📄 documentation
