Repository TheWorldAvatar/stack, pull requests merged in 2025-04, with the labels that each got.

#17 16 create outgoing federated pre stack
  stack-clients/docker-compose.yml
  stack-clients/pom.xml
  stack-clients/src/main/java/com/cmclinnovations/stack/clients/docker/DockerConfigHandler.java
  stack-clients/src/main/java/com/cmclinnovations/stack/clients/rdf4j/ExternalEndpointConfig.java
  stack-clients/src/main/java/com/cmclinnovations/stack/clients/rdf4j/Rdf4jEndpointConfig.java
  stack-clients/src/main/java/com/cmclinnovations/stack/services/ContainerService.java
  stack-clients/src/main/java/com/cmclinnovations/stack/services/Rdf4jService.java
  stack-data-uploader/docker-compose.yml
  stack-data-uploader/pom.xml
  stack-manager/README.md
  stack-manager/docker-compose.yml
  stack-manager/inputs/config/external_endpoints/.gitignore
  stack-manager/pom.xml
Labels: enhancement

#23 RDF4J repos persist on restart
  stack-clients/docker-compose.yml
  stack-clients/pom.xml
  stack-clients/src/main/resources/com/cmclinnovations/stack/services/built-ins/rdf4j.json
  stack-data-uploader/docker-compose.yml
  stack-data-uploader/pom.xml
  stack-manager/docker-compose.yml
  stack-manager/pom.xml
Labels: bug

#25 Removed copying repository
  stack-clients/docker-compose.yml
  stack-clients/pom.xml
  stack-clients/src/main/java/com/cmclinnovations/stack/clients/rdf4j/Rdf4jClient.java
  stack-data-uploader/docker-compose.yml
  stack-data-uploader/pom.xml
  stack-manager/docker-compose.yml
  stack-manager/pom.xml
Labels: bug

#26 Hotfix Podman health check
  stack-clients/docker-compose.yml
  stack-clients/pom.xml
  stack-clients/src/main/java/com/cmclinnovations/stack/services/PodmanService.java
  stack-data-uploader/docker-compose.yml
  stack-data-uploader/pom.xml
  stack-manager/docker-compose.yml
  stack-manager/pom.xml
Labels: 🐛 bug, ✨ enhancement
